name: Node.js CI

on: [push]

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm test
        env:
          CI: true
      - run: 'echo ${{ github.ref }}'
      - run: 'git push --dry-run https://github.com/digitalroute/plutt.git HEAD:master'
      - if: github.ref == 'refs/heads/master'
        run: npm run semantic-release
