name: Node.js CI

on: [push]

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm test
        env:
          CI: true
      - run: 'echo ${{ github.ref }}'
      - if: github.ref == 'refs/heads/master'
        name: Add ssh deploy key (for semantic-release)
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
          run: |
            mkdir ~/.ssh
            echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      - run: 'git push --dry-run git@github.com:digitalroute/plutt.git HEAD:master'
      - if: github.ref == 'refs/heads/master'
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
